### ISSUE TITLE
RCO query broken

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/zoning-appeals#7] opened 2015-01-09 19:53 UTC
The RCO query currently returns a `400` with the error `Invalid or missing input parameters.`

The URL being hit is:

```
http://gis.phila.gov/arcgis/rest/services/PhilaGov/RCO/MapServer/0/query?where=1%3D1&outFields=ORG_NAME&returnGeometry=true&returnIdsOnly=false&returnCountOnly=false&orderByFields=ORG_NAME&returnZ=false&returnM=false&returnDistinctValues=false&f=pjson
```

This can be changed in [config.js#L31](https://github.com/CityOfPhiladelphia/zoning-appeals/blob/master/app/scripts/config.js#L31)

**Comment by jamesmbentley** [comment] 2015-01-09 20:02
The query should be changed to the following:
```
http://gis.phila.gov/arcgis/rest/services/PhilaGov/RCO/MapServer/0/query?where=1%3D1&outFields=ORGANIZATION_NAME&returnGeometry=true&returnIdsOnly=false&returnCountOnly=false&orderByFields=ORGANIZATION_NAME&returnZ=false&returnM=false&returnDistinctValues=false&f=pjson
```
We updated that layer for the Planning Department last Sunday and the field ORG_NAME was removed, because it was a duplicate of ORGANIZATION_NAME

**Comment by timwis** [comment] 2015-01-09 20:26
Still need to build and push to `gh-pages`

**Comment by jamesmbentley** [comment] 2015-01-12 16:15
Tim did the new build get pushed to Github pages yet?

**Closed** 2015-01-12 19:36 UTC
Labels: bug
